version: '2'
services:
  vlo_solr_init:
    image: registry.gitlab.com/clarin-eric/docker-vlo-beta:1.3.5
    entrypoint: ["sleep", "1"]
    user: solr
    volumes:
      # this copies data for Solr home directory provisioning
      - solr-home-provisioning:/opt/vlo/solr/vlo-solr-home
    restart: "no"
  vlo_solr:
    image: registry.gitlab.com/clarin-eric/docker-solr:1.0.0
    environment:
      - SOLR_DATA_HOME=/solr-data
    depends_on:
      - vlo_solr_init # to ensure Solr home directory content
    entrypoint: ["bash", "-c", "[ -f /docker-entrypoint-initsolr.d/solr_home/solr.xml ]
                        && /usr/bin/entrypoint.sh"]
    volumes:
      - solr-home-provisioning:/docker-entrypoint-initsolr.d/solr_home
      - vlo-solr-data:/solr-data
    ports:
      - 8983:8983
    restart: unless-stopped
    networks:
        - network_vlo
  vlo_web:
    image: registry.gitlab.com/clarin-eric/docker-vlo-beta:1.3.5
    environment:
      - VLO_DOCKER_SOLR_URL=http://vlo_solr:8983/solr/vlo-index/
      - VLO_DOCKER_PUBLIC_HOME_URL=http://localhost:8080
      - VLO_DOCKER_PIWIK_ENABLE_TRACKER=false
      - VLO_DOCKER_DATAROOTS_FILE=dataroots.xml
    volumes:
      - ./include/dataroots.xml:/opt/vlo/config/dataroots.xml
      - ./include/run-import.sh:/app/run-import.sh
    ports:
      - 8181:8080
    restart: unless-stopped
    networks:
        - network_vlo
volumes:
    solr-home-provisioning:
        external: false
    vlo-solr-data:
        external: false
networks:
  network_vlo:
